services:
  wazzup-service:
    container_name: wazzup_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1242:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - wazzup_network

  postgres:
    image: postgres:15
    container_name: wazzup_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data_rust:/var/lib/postgresql/data
    networks:
      - wazzup_network

  dbgate:
    image: dbgate/dbgate
    container_name: wazzup_dbgate
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DBGATE_DATABASE_URL=postgres://postgres:password123@postgres:5432/main
    networks:
      - wazzup_network

networks:
  wazzup_network:
    driver: bridge

volumes:
  postgres_data_rust: