//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "client_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::client_tag_assignments::Entity")]
    ClientTagAssignments,
}

impl Related<super::client_tag_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientTagAssignments.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        super::client_tag_assignments::Relation::Clients.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::client_tag_assignments::Relation::ClientTags
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
