//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "client_tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub id: Vec<u8>,
    #[sea_orm(unique)]
    pub value: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::client_tag_assignments::Entity")]
    ClientTagAssignments,
}

impl Related<super::client_tag_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ClientTagAssignments.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
