//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "services")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub id: Vec<u8>,
    pub name: String,
    #[sea_orm(column_type = "Binary(16)", nullable)]
    pub company_id: Option<Vec<u8>>,
    pub duration: i32,
    pub price: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub image_path: Option<String>,
    pub is_active: i8,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bookings::Entity")]
    Bookings,
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::CompanyId",
        to = "super::companies::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Companies,
    #[sea_orm(has_many = "super::service_required_roles::Entity")]
    ServiceRequiredRoles,
}

impl Related<super::bookings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bookings.def()
    }
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}

impl Related<super::service_required_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServiceRequiredRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
