//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ToSchema)]
#[sea_orm(table_name = "companies")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub name: String,
    pub description: Option<String>,
    pub email: String,
    pub phone: Option<String>,
    pub database_name: String,
    pub wazzup_api_key: String,
    pub is_active: Option<bool>,
    #[schema(value_type = String, format = DateTime)]
    pub created_at: Option<DateTimeWithTimeZone>,
    #[schema(value_type = String, format = DateTime)]
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub subscription_tier: Option<String>,
    pub max_locations: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
