//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub mod prelude;

pub mod availability_exceptions;
pub mod booking_resources;
pub mod bookings;
pub mod client_tag_assignments;
pub mod client_tags;
pub mod clients;
pub mod locations;
pub mod projects;
pub mod resource_roles;
pub mod resources;
pub mod schedule_templates;
pub mod service_required_roles;
pub mod services;
pub mod task_assignments;
pub mod task_statuses;
pub mod tasks;
pub mod tokens;
pub mod users;
pub mod wazzup_channels;
pub mod wazzup_chats;
pub mod wazzup_messages;
pub mod wazzup_settings;
pub mod wazzup_transfers;
