//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub project_id: i64,
    pub parent_task_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub content: Option<Json>,
    pub status_id: i64,
    pub previous_task_id: Option<i64>,
    pub route: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Projects,
    #[sea_orm(has_many = "super::task_assignments::Entity")]
    TaskAssignments,
    #[sea_orm(
        belongs_to = "super::task_statuses::Entity",
        from = "Column::StatusId",
        to = "super::task_statuses::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TaskStatuses,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentTaskId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef2,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::PreviousTaskId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef1,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::task_assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskAssignments.def()
    }
}

impl Related<super::task_statuses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskStatuses.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::task_assignments::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::task_assignments::Relation::Tasks.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
