//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wazzup_channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::wazzup_chats::Entity")]
    WazzupChats,
    #[sea_orm(has_many = "super::wazzup_settings::Entity")]
    WazzupSettings,
}

impl Related<super::wazzup_chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WazzupChats.def()
    }
}

impl Related<super::wazzup_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WazzupSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
