//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

pub use super::availability_exceptions::Entity as AvailabilityExceptions;
pub use super::booking_resources::Entity as BookingResources;
pub use super::bookings::Entity as Bookings;
pub use super::client_tag_assignments::Entity as ClientTagAssignments;
pub use super::client_tags::Entity as ClientTags;
pub use super::clients::Entity as Clients;
pub use super::locations::Entity as Locations;
pub use super::projects::Entity as Projects;
pub use super::resource_roles::Entity as ResourceRoles;
pub use super::resources::Entity as Resources;
pub use super::schedule_templates::Entity as ScheduleTemplates;
pub use super::service_required_roles::Entity as ServiceRequiredRoles;
pub use super::services::Entity as Services;
pub use super::task_assignments::Entity as TaskAssignments;
pub use super::task_statuses::Entity as TaskStatuses;
pub use super::tasks::Entity as Tasks;
pub use super::tokens::Entity as Tokens;
pub use super::users::Entity as Users;
pub use super::wazzup_channels::Entity as WazzupChannels;
pub use super::wazzup_chats::Entity as WazzupChats;
pub use super::wazzup_messages::Entity as WazzupMessages;
pub use super::wazzup_settings::Entity as WazzupSettings;
pub use super::wazzup_transfers::Entity as WazzupTransfers;
