//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wazzup_settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub wazzup_user_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub wazzup_channel_id: String,
    pub role: String,
    pub receives_messages: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::wazzup_channels::Entity",
        from = "Column::WazzupChannelId",
        to = "super::wazzup_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WazzupChannels,
}

impl Related<super::wazzup_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WazzupChannels.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
