//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wazzup_chats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub channel_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::clients::Entity")]
    Clients,
    #[sea_orm(
        belongs_to = "super::wazzup_channels::Entity",
        from = "Column::ChannelId",
        to = "super::wazzup_channels::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WazzupChannels,
    #[sea_orm(has_many = "super::wazzup_messages::Entity")]
    WazzupMessages,
    #[sea_orm(has_many = "super::wazzup_transfers::Entity")]
    WazzupTransfers,
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::wazzup_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WazzupChannels.def()
    }
}

impl Related<super::wazzup_messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WazzupMessages.def()
    }
}

impl Related<super::wazzup_transfers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WazzupTransfers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
